### ISSUE TITLE
can this project run on raspberry pi 2b?

### ISSUE THREAD

**Issue by miroskv** [rust-embedded/rust-raspberrypi-OS-tutorials#108]
I only have an raspberry pi 2b,I wonder if this project can run on pi 2b?

**Comment by andre-richter** [comment]
The whole project is laid out to support only `64 bit` processor architectures.

According to Wikipedia, there exists two version of the Pi2:
- `Raspberry Pi 2 Mod. B (AArch32)`
- `Raspberry Pi 2 Mod. B v1.2 (AArch64)`

The `v1.2` seems to have the same CPU than the Pi3. So maybe some adaptions are needed to the BSP code, but in theory the `v1.2` could work.

**Comment by andre-richter** [comment]
Closing for the time being. Please reopen if you have follow-up questions.
