### ISSUE TITLE
中文Readme中 USB串口供电描述

### ISSUE THREAD

**Issue by tmsi-io** [rust-embedded/rust-raspberrypi-OS-tutorials#123]
```
USB 串行输出

由于教程中开发的内核是在真实的硬件上运行的，因此强烈建议您使用 USB 串行调试线来进行试验。连接后调试线会为树莓派供电， 所以不需要额外供电。
```
调试线会为数梅派供电？ 图里没看到有对应接入

**Comment by andre-richter** [comment]
It might be an old translation, I cannot tell at the moment.

The only supported way is to power the Raspberrys over the external USB cable and connect as depicted in https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials#-usb-serial-output

**Comment by colachg** [comment]
@tmsi-io 调试线另一头有个micro USB-A的口，它可以供电的。你可以某宝搜下：USB转TTL串口就知道了。
