### ISSUE TITLE
a stupid question: how to boot up the qemu.

### ISSUE THREAD

**Issue by lllsssskkk** [rust-embedded/rust-raspberrypi-OS-tutorials#141]
i've been encountered a problem every time i run the `make qemu` . 

![image](https://user-images.githubusercontent.com/32951648/151196306-aaacbd82-a6d5-4fb8-8287-755b95e5fdb9.png)

i really  dont think such image exists in the docker hub.

any hints guide me through?pls

**Comment by andre-richter** [comment]
What is your execution environment?
the `\n` that get printed look like there might be something odd.

Can you show what gets printed when you remove the `@` in `@$(DOCKER_QEMU) $(EXEC_QEMU) $(QEMU_RELEASE_ARGS) -kernel $(KERNEL_BIN)` in `Makefile`.

**Comment by lllsssskkk** [comment]
Hey 
   thx for your reply. The followings are bunches of images, hope they are relevant to the question.

my system info :
![image](https://user-images.githubusercontent.com/32951648/151549918-46c4ca5e-46ab-4648-b416-826b0029e6c6.png)

my docker version: 
![image](https://user-images.githubusercontent.com/32951648/151550062-2c5b7ca1-2712-462e-8b55-40899bb7dbc4.png)

my rust version 
![image](https://user-images.githubusercontent.com/32951648/151550167-b7469afb-3a45-4426-8e50-46cc544455e7.png)

after deleting the at symbol. make qemu code in the makefile :
![image](https://user-images.githubusercontent.com/32951648/151550603-d588eacc-4f93-418e-8546-c66b70981091.png)

the output of running `make qemu` with modified makefile

![image](https://user-images.githubusercontent.com/32951648/151551620-bd96bafb-0739-4196-aed4-61ffcf44fdf1.png)

just another silly question.

In an ideal situation, all we'd have to do to start the qemu is install docker and rust and run'make qemu' in each folder. 

Is there anything else I should do before calling'make qemu'?

**Comment by andre-richter** [comment]
The emitted command line looks correct. Maybe your local docker setup is in a bad state.

Can you try ‚`docker logout` once before testing again.

**Comment by lllsssskkk** [comment]
unfortunately, the problem remains after logging out. The output is still the same, complaining cant pull the year image

**Comment by andre-richter** [comment]
What happens when you do `docker pull rustembedded/osdev-utils:2021.12` in your terminal?

**Comment by lllsssskkk** [comment]
I can pull the image without errors

![image](https://user-images.githubusercontent.com/32951648/151703279-5b375256-f339-46e7-9aba-38c5ea90f45b.png)


Is there a way in Docker to build the container using an existing image rather than pulling it from the hub again?

**Comment by andre-richter** [comment]
There aren’t many options left where it goes wrong.

the print of the docker command that make generates looks good. Could can pull the image when invoking docker manually.

The printing of `\n` indicates something with the shell in which make gets executed.
Which shell are you using?

can you execute `bash` once before executing `make`. Does that help?

**Comment by lllsssskkk** [comment]
If it looks like to me that only my machine has this kinda of problem, i must set something wrong in my env. 

As i realised i have all tools needed to build the image. I decide to manually load the image into the qemu.  Since i figure out how to load the image with qemu, i decide to close this issue. Thx for your help, :D.
