### ISSUE TITLE
invalid file operation error

### ISSUE THREAD

**Issue by EWYan** [rust-embedded/rust-raspberrypi-OS-tutorials#163]
i just try to compile 01_wait_forever samples on ubuntu1604, but don't know why the following error pops out:
```
yan@ubuntu:~/Desktop/rust-raspberrypi-OS-tutorials/01_wait_forever$ make qemu
Makefile:120: *** Invalid file operation: < target/aarch64-unknown-none-softfloat/release/kernel.d.  Stop.
```
please help, thx.

**Comment by andre-richter** [comment]
Hmm interesting. Did you change anything or is every file untouched?

What is the output of `make —version`?

**Comment by andre-richter** [comment]
Probably a make version that is too old. Can you try this as a workaround for now: 

https://stackoverflow.com/questions/6767413/create-a-variable-in-a-makefile-by-reading-contents-of-another-file#6779306

**Comment by EWYan** [comment]
> Probably a make version that is too old. Can you try this as a workaround for now:
> 
> https://stackoverflow.com/questions/6767413/create-a-variable-in-a-makefile-by-reading-contents-of-another-file#6779306

yes, make 4.1 is not works for this file operation, make 4.3 works like charm; thanks.
