### ISSUE TITLE
I want to know about other microcontrollers, you can refer to this example

### ISSUE THREAD

**Issue by Jzow** [rust-embedded/rust-raspberrypi-OS-tutorials#168]
I have a development board of esp32-c3-rust. I want to do some development on it. I have seen the example of ESP IDF

**Comment by Jzow** [comment]
@eldruin Hi, can I do this

**Comment by eldruin** [comment]
Hi @Jzow I would refer you to the support project about that microcontroller:
https://github.com/esp-rs/esp-hal/tree/main/esp32c3-hal
You can find some examples there.

Closing as unrelated.

**Comment by Jzow** [comment]
@eldruin thanks, I will find a raspberry pie to study
