### ISSUE TITLE
chapter 6 can not get correct output, stuck at: [ML] Requesting binary

### ISSUE THREAD

**Issue by Tim-C1** [rust-embedded/rust-raspberrypi-OS-tutorials#177]
I am using rasberry Pi 3a, the first 5 chapters are ok but I can not get correct ouput for chapter 6.
This is the result
![image](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/assets/80671548/22d3db1c-6ef3-41d3-b88c-6fda3251f630)

I don't know where should I begin to debug, please help!

Oh, it also seems that I cannot echo input in Chapter5, I think that's because clear_rx or read_char is blocking

**Comment by SikkiLadho** [comment]
Were you able to fix this? I am still having this issue.
