### ISSUE TITLE
Error regarding Github CI/CD

### ISSUE THREAD

**Issue by Jzow** [rust-embedded/rust-raspberrypi-OS-tutorials#184]
I have noticed that every time a PR is performed, the Github CI/CD program performs status checks, and it seems to report an issue with copyright years in the Makefile file

example:

```shell
Clippy X1_JTAG_boot - BSP: rpi4
   Compiling mingo v0.8.0 (/home/runner/work/rust-raspberrypi-OS-tutorials/rust-raspberrypi-OS-tutorials/X1_JTAG_boot)
    Checking tock-registers v0.8.1
    Checking aarch64-cpu v9.0.0
    Finished release [optimized] target(s) in 2.17s
Checking for copyright: 01_wait_forever/Makefile
	Only found years: [2018, 2022]
Error: Process completed with exit code 1.
```

https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/49a25275e66ab0dcacfcbbbb666311df7a9650c9/01_wait_forever/Makefile#L3

But I'm not sure if it caused it error.

**Comment by Jzow** [comment]
#188

**Comment by eldruin** [comment]
It is probably complaining that `2023` is not present. Adding it may fix it.

**Comment by Jzow** [comment]
> It is probably complaining that `2023` is not present. Adding it may fix it.

Okay, I'll add it later and resubmit the PR.
