### ISSUE TITLE
Depracated link in The tl;dr Version subsection of README.md file

### ISSUE THREAD

**Issue by nmpluta** [rust-embedded/rust-raspberrypi-OS-tutorials#197]
The link provided in the [🚀 Version tl;dr](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/README.md#-the-tldr-version) section `System Requirements` in `README.md` seems to be deprecated. It concerns the link to `rust-toolchain` mentioned in point 3: 
> Prepare the Rust toolchain. Most of it will be handled on first use through the [rust-toolchain](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/rust-toolchain) file. What's left for us to do is:

![image](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/assets/80521103/80b55046-0746-4b1f-8e5e-22a1f83835aa)

**Comment by eldruin** [comment]
Nice find. The `.toml` part of the URL got removed. 
The right URL is this one: https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/rust-toolchain.toml
Could you submit a PR fixing this?

**Comment by nmpluta** [comment]
> Nice find. The `.toml` part of the URL got removed. The right URL is this one: https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/rust-toolchain.toml Could you submit a PR fixing this?

Sure. Here's PR: #199
