### ISSUE TITLE
Please Change README

### ISSUE THREAD

**Issue by friendbear** [rust-embedded/rust-raspberrypi-OS-tutorials#206]
Please change the link to the licensee from http to https.

<https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials?tab=readme-ov-file#license>

**Comment by eldruin** [comment]
Done, thanks.

**Comment by friendbear** [comment]
ありがとうございます。すごくワクワクしてます！
rassbeerry piのファンなのです。
![IMG_8704 (1)](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/assets/4956799/290a51b6-dff4-437e-82aa-c44f3f0979ea)
