### ISSUE TITLE
Why use Makefile handle build process?

### ISSUE THREAD

**Issue by fanyxok** [rust-embedded/rust-raspberrypi-OS-tutorials#207]
Hello,

Other tools like CMake, Meson and soon, or rust's builtin toolchain. They can also deal with this situnation.

Why choose Makefile?

I don't mean Makefile is not good, I am just curious about that.

**Comment by eldruin** [comment]
Hi,
Probably because `make` is there by default in any unix platform, it is "simple" (certainly at the start) and so on.
I will close this issue since it is not actionable but feel free to reopen it if you have additional questions.
