### ISSUE TITLE
Update README.CN.md

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/rust-raspberrypi-OS-tutorials#52]
Hi @colachg and @readlnh ,

In #51, the READMEs got updated. If you like, you can have a look.

Also, there is https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/master/00_before_we_start/README.md now.

Best,
Andre

**Comment by andre-richter** [comment]
Ping @colachg @readlnh ?

**Comment by colachg** [comment]
#55

**Comment by readlnh** [comment]
I'm sorry, I didn't notice this until now. I have reviewed the README.CN.md, it seems ok to me.

**Comment by colachg** [comment]
Maybe you could watch it. :)

**Comment by readlnh** [comment]
> Maybe you could watch it. :)

I will open a pull request tonight

**Comment by andre-richter** [comment]
Closed by #59
