### ISSUE TITLE
Unexpected Error: #<Errno::EINVAL: Invalid argument - tcsetattr>

### ISSUE THREAD

**Issue by sachaos** [rust-embedded/rust-raspberrypi-OS-tutorials#95]
I have a problem when trying 06_drivers_gpio_uart.
I got following error.

```
$ DEV_SERIAL=/dev/tty.usbserial-1420 make miniterm

Miniterm 1.0


[MT] ⚡ Unexpected Error: #<Errno::EINVAL: Invalid argument - tcsetattr>

[MT] Bye 👋
```

I think the cause of the error is `baud`.
The baud is depending on the platform according to the documentation.
I'm using Mac OS.

> Integer from 50 to 256000, depending on platform)
> https://rubydoc.info/gems/serialport/SerialPort:set_modem_params

The current value is `576000`

https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/ff382c3fafa6257e37c208015cbea3aa3d1b2515/utils/miniterm.rb#L44

## Reproduce process

1. Use Mac OS.
1. Compile source.
1. Write binary to SD card.
1. Power on.
1. Run miniterm.

**Comment by andre-richter** [comment]
Ah, I didn’t know macOS was more restrictive.
That’s a pity.

Does Miniterm start if you set it to 256000? (You wouldn’t see sane output though, because the Kerne binary is hardcoded to 576000.

**Comment by andre-richter** [comment]
I read up a bit on it. Seems macOS usually doesn’t allow more than 230400 when opening the device, but it seems there is a way to circumvent it using stty.

Can you do a test for me?

1. change the baudrate in miniterm.rb back to 230400.
2. Start the Miniterm.
3. In a different console, execute `stty -f /dev/USB_SERIAL_NAME 576000`
4. Only now power the RPi and check if you can see the console output.

**Comment by sachaos** [comment]
@andre-richter 

> Does Miniterm start if you set it to 256000? (You wouldn’t see sane output though, because the Kerne binary is hardcoded to 576000.
Yes. It works fine when I revert `ee52e8e288ef6f00416eed94921c2b0e1acfab73`

```
❯ DEV_SERIAL=/dev/tty.usbserial-1420 make miniterm
Miniterm 1.0

[MT] ✅ Serial connected
[0] Booting on: Raspberry Pi 4
[1] Drivers loaded:
      1. BCM GPIO
      2. BCM PL011 UART
[2] Chars written: 93
[3] Echoing input now
kjkdsafdsa

[MT] Bye 👋
```

I'll try the test using stty.

**Comment by sachaos** [comment]
@andre-richter It seems `576000` is invalid value on macOS.

```
stty -f /dev/tty.usbserial-1420 576000
stty: tcsetattr: Invalid argument
```

The value `460800` which is mentioned in the stackoverflow was valid.

```
$ stty -f /dev/tty.usbserial-1420 460800

~
$ echo $?
0
```

**Comment by andre-richter** [comment]
Thanks!

Then I might need to make the whole tutorials use 460800 to solve this issue and adapt miniterm.rb to spawn the stty when on macOS.

**Comment by sachaos** [comment]
@andre-richter I've created PR to fix this problem.
I've checked it works on my macOS.

Please review & merge it If it looks good. #96

**Comment by andre-richter** [comment]
Hi @sachaos,

could you please try out https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/pull/97 on your Mac and tell me if it works?
I bumped to 921_600 baud + some more fixes.

I added you as co-author of this new PR to credit your findings.

**Comment by sachaos** [comment]
@andre-richter Thank you! I'll try the PR.
